services:
  
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlGetInIt
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "GetInIt1234"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver:/var/lib/sqlserver/data
volumes:
  sqlserver: